# ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# # `app.yaml`
# client | Semantyk
#
# This file is used to configure the Google Cloud Platform App Engine service.
#
# Created: Nov 29, 2023
# Modified: Jul 5, 2024
#
# Author: Semantyk Team
# Maintainer: Daniel Bakas <https://id.danielbakas.com>
#
# Copyright © Semantyk 2024. All rights reserved.
# ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

runtime: nodejs20
env: standard
instance_class: F1
automatic_scaling:
  max_instances: 1