# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# # `app.yaml`
# client | Semantyk
#
# Created: Nov 29, 2023
# Modified: Dec 13, 2023
#
# Author(s): Semantyk Team
# Maintainer(s): Daniel Bakas <https://id.danielbakas.com>
#
# Copyright © Semantyk 2023. All rights reserved.
# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

runtime: nodejs20
env: standard
instance_class: F1
automatic_scaling:
  max_instances: 1