# ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# # `app.yaml`
# @organization: Semantyk
# @project: client
#
# @file: This file is used to configure the Google Cloud Platform App Engine
# service.
#
# @created: Nov 29, 2023
# @modified: Sep 18,2024
#
# @author: Semantyk Team
# @maintainer: Daniel Bakas <https://id.danielbakas.com>
#
# @copyright: Copyright © Semantyk 2024. All rights reserved.
# ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

runtime: nodejs20
env: standard
instance_class: F1
automatic_scaling:
  max_instances: 1