# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# # `bug_report.yaml` | Issue Templates
# client | Semantyk
#
# This file contains the GitHub template for reporting a bug in Semantyk.
#
# Created: Dec 9, 2023
# Modified: Jul 5, 2024
#
# Author: Semantyk Team
# Maintainer: Daniel Bakas <https://id.danielbakas.com>
#
# Copyright © Semantyk 2024. All rights reserved.
# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

name: 🐛 Bug | Report
title: "🐛 Bug | {Replace this with title}"
description: Report a bug in Semantyk
labels: [ bug ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers`
      render: shell
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Package Manager
      description: Select the package manager.
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        # TODO: Add links to the Code of Conduct
        - label: Follow our [Code of Conduct]()
          required: true
        # TODO: Add links to the Contributing Guidelines
        - label: Read the [Contributing Guidelines]().
          required: true
        # TODO: Add links to the Documentation
        - label: Read the [docs]().
          required: true
        - label: Check that there isn't [already an issue](https://github.com/semantyk/client/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/semantyk/client/discussions).
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true