# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# # `dev.yaml`
# @organization: Semantyk
# @project: client
#
# @file: This file contains the GitHub Actions workflow for the development CI.
#
# @created: Nov 29, 2023
# @modified: Mar 7, 2025
#
# @author: Semantyk Team
# @maintainer: Daniel Bakas <https://id.danielbakas.com>
#
# @copyright: Semantyk © 2025. All rights reserved.
# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

name: Development CI Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the Repository
      - uses: actions/checkout@v4
        name: 1. Repository Checkout
      # 2. Setup Bun
      - uses: oven-sh/setup-bun@v2
        name: 2. Setup Bun
      # 3. Install Dependencies
      - run: bun install --frozen-lockfile
        name: 3. Install Dependencies
      # 4. Run Tests
      - run: bun test
        name: 4. Run Tests
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # 1. Checkout the Repository
      - uses: actions/checkout@v4
        name: 1. Repository Checkout
      # 2. Setup Bun
      - uses: oven-sh/setup-bun@v2
        name: 2. Setup Bun
      # 3. Install Dependencies
      - run: bun install --frozen-lockfile
        name: 3. Install Dependencies
      # 4. Build
      - run: bun run build
        name: 4. Build
